name: machine_learning
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias necesarias
  tflite: ^1.1.1
  image_picker: ^0.6.7+6
  soundpool: ^1.1.1
  gestures: ^0.0.1

  cupertino_icons: ^0.1.3
  url_launcher: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Machine Learning es fácil"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/models/
    - assets/sounds/
